### ISSUE TITLE
Server-side rendering returns error: "window" is not available during server side rendering.

### ISSUE THREAD

**Issue by finmoorhouse** [mmkari/react-star-picker#14]
I tried adding this start picker to my Gatsby site, and it works great in development. Unfortunately it seems to rely on access to the window, which isn't available when the site is generated in production using Netlify. So I get the following error —

``WebpackError: ReferenceError: window is not defined``

Happy to send a more detailed error log. The site is [here](https://github.com/finmoorhouse/hearthisidea.com). Thanks.

**Comment by mmkari** [comment]
Hi and thanks for the message!

I looked around and a third-party dependency (`classnames`) of this module does in fact rely on access to window as you described.

I'll see what the best long-term solution would be to make this library support SSR directly but in the meantime there seems to be an easy general solution to these issues in using `loadable-components`:
```
npm install @loadable/component
```
then, instead of importing from `react-star-picker`, define and import from this wrapper file:
```jsx
import React from "react"
import Loadable from "@loadable/component"

export default Loadable(() => import("react-star-picker"), {
  ssr: false,
})
```
I tested it to work in production with Gatsby as hosted on GH Pages:
https://mmkari.github.io/soap-co/test/

(source:
https://www.gatsbyjs.com/docs/using-client-side-only-packages/#workaround-3-load-client-side-dependent-components-with-loadable-components)

**Comment by finmoorhouse** [comment]
Hi, thanks so much for getting back on this! Your suggestion sounds great — I'll give it a try soon.
