### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by theDanielJLewis** [mmkari/react-star-picker#52]
I'm running Next.js 14.1 and getting this error message in my server console:

```
node_modules/.pnpm/react-star-picker@2.1.3_react-dom@18.2.0_react@18.2.0/node_modules/react-star-picker/dist/index.js (2:298) @ self
 ⨯ ReferenceError: self is not defined
```

The component still seems to work, but the error is concerning for production.

**Comment by mmkari** [comment]
Hi and thanks for posting the issue.

I don't have an environment at hand to reproduce the error myself but it seems to be caused by Webpack's default behavior when building a library as a UMD module. Apparently, I was missing an additional configuration (`globalObject`) that is needed to make the build work on the server side too. (https://webpack.js.org/configuration/output/#outputglobalobject)

I made that fix and published a new version `2.1.4` of this library. Please let me know if that fixes the error.

**Comment by theDanielJLewis** [comment]
Thanks. _That_ error is gone, but now another one took its place:

```
 ⨯ node_modules/.pnpm/react-star-picker@2.1.4_react-dom@18.2.0_react@18.2.0/node_modules/react-star-picker/dist/index.js (2:3967) @ document
 ⨯ ReferenceError: document is not defined
```

**Comment by Kickbykick** [comment]
Yeah, I have the same issue.

**Comment by mmkari** [comment]
I looked into the problem and it's related to client and server components. This library is a client component library and cannot be rendered on the server side.

The recommended way for library authors to indicate specific components as client side components is to add the `use client` directive to the relevant component files. I did that in the previous release but didn't realize Webpack would remove those directives during bundling.

I just now released a new version that uses additional Webpack plugins to add the required directive to the final bundle and hopefully fixes the aforementioned issues. Please let me know if it works.


I will be releasing a new Rollup bundle later in the next version, but meanwhile there's also a way you can fix these rendering issues yourself: https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-third-party-packages-and-providers

**Comment by theDanielJLewis** [comment]
Latest update doesn't seem to fix the problem.

The star rating component appears in a component that's already declaring `"use client"`, and I even added that to my custom StarRating component, but the `document is not defined` error still occurs.

Interesting, this doesn't seem to prevent the page from loading or even functioning for users, but it _is_ causing a server error for my uptime monitor.

If you need it, here's what my custom component looks like now:

```ts
"use client";
import { cn } from "@/lib/utils";
import { BiSolidStar, BiStar } from "react-icons/bi";
import StarPicker from "react-star-picker";

const MyCustomStarRenderer = ({
  index,
  selectedIndex,
  hoverIndex,
  className, // provided by styled-component, need to attach to element
}) => {
  // style the "star" according to the given index, selectedIndex, hoverIndex...
  const selected = index <= selectedIndex;
  const inHoverRange = hoverIndex != null && index <= hoverIndex;
  const hoverActive = hoverIndex != null;
  const isHovered = hoverIndex === index;

  if (hoverActive && isHovered) {
    return <BiSolidStar className={cn(className, "")} />;
  } else if (selected || inHoverRange) {
    return <BiSolidStar className={cn(className, "")} />;
  }
  return <BiStar className={cn(className, "")} />;
};

export const StarRating = ({
  value,
  onChange,
  name,
  className,
  size = 40,
  numberStars = 5,
  disabled = false,
  halfStars = false,
  resettable = true,
}: {
  value: number;
  onChange: () => void;
  name?: string;
  className?: string;
  size?: number;
  numberStars?: number;
  disabled?: boolean;
  halfStars?: boolean;
  resettable?: boolean;
}) => {
  //
  return (
    <StarPicker
      value={value}
      onChange={onChange}
      name={name}
      className={cn("MyStarPicker", className)}
      size={size}
      numberStars={numberStars}
      disabled={disabled}
      halfStars={halfStars}
      resettable={resettable}
      starRenderer={MyCustomStarRenderer}
    />
  );
};
```

**Comment by mmkari** [comment]
Hi @theDanielJLewis and thanks for the help.

The error which you reported turned out to be caused by a Webpack loader, the `style-loader`, that was used to bundle all the component's styles together with the code into a single UMD bundle. This loader included some runtime logic into the final bundle whose purpose was to inject the included styles into the client's DOM without the client having to import them separately. This however fails on the server side where browser APIs, e.g. the `document`, are not available.

As a result, I worked up an ES module bundle that exports the component and its styles separately. So, now, the styles need to be imported separately from `'react-star-picker/styles.css'` as shown in the example in the updated README. This is best done in the wrapper file that you posted in your previous message.

With this new approach in version `3.0.0`, Next should be able to bundle the imported library JS and CSS into your app's bundle however it needs to.

I expect that this fix resolved the reported issue and I will close it after one week unless there's still a problem. I'm thankful for any feedback.

**Comment by theDanielJLewis** [comment]
Wonderful! That seems to have fixed the problem. Thank you!

I'm running into some other breaking changes, and I noticed the documentation site isn't updated for version 3. But I'm troubleshooting before I open a new issue.
